---
- name: Deploy ShopSphere
  hosts: production
  become: true
  vars:
    compose_file: "{{ app_dir }}/docker-compose.yml"

  tasks:
    - name: Create application directory
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"

    - name: Copy production compose file
      ansible.builtin.template:
        src: ../templates/docker-compose.prod.yml.j2
        dest: "{{ compose_file }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"

    - name: Copy Nginx configuration
      ansible.builtin.copy:
        src: ../../nginx/nginx.conf
        dest: "{{ app_dir }}/nginx.conf"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"

    - name: Copy Docker Compose file
      ansible.builtin.copy:
        src: ../../docker-compose.yml
        dest: "{{ compose_file }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"  

    - name: Create environment file
      ansible.builtin.template:
        src: ../templates/app.env.j2
        dest: "{{ app_dir }}/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"

    - name: Pull images and start application
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}"
        pull: always
        state: present
